[2025-06-04T09:11:46.484+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-04T09:11:46.508+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_extraction_pipeline.load_data_to_postgres manual__2025-06-04T09:11:13+00:00 [queued]>
[2025-06-04T09:11:46.512+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_extraction_pipeline.load_data_to_postgres manual__2025-06-04T09:11:13+00:00 [queued]>
[2025-06-04T09:11:46.512+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-04T09:11:46.519+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_to_postgres> on 2025-06-04 09:11:13+00:00
[2025-06-04T09:11:46.526+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=228) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-04T09:11:46.525+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_extraction_pipeline', 'load_data_to_postgres', 'manual__2025-06-04T09:11:13+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/f1_pipeline.py', '--cfg-path', '/tmp/tmpp5w5rwap']
[2025-06-04T09:11:46.526+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask load_data_to_postgres
[2025-06-04T09:11:46.526+0000] {standard_task_runner.py:63} INFO - Started process 229 to run task
[2025-06-04T09:11:46.555+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_extraction_pipeline.load_data_to_postgres manual__2025-06-04T09:11:13+00:00 [running]> on host d0166d009751
[2025-06-04T09:11:46.749+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_extraction_pipeline' AIRFLOW_CTX_TASK_ID='load_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-04T09:11:13+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-04T09:11:13+00:00'
[2025-06-04T09:11:46.749+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-04T09:11:46.754+0000] {logging_mixin.py:188} INFO - ❗ ERREUR : Les variables d'environnement PG_DATABASE, PG_USER, et PG_PASSWORD doivent être définies.
[2025-06-04T09:11:46.755+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-04T09:11:46.755+0000] {taskinstance.py:2907} ERROR - Task failed due to SystemExit(1)
[2025-06-04T09:11:46.760+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=f1_data_extraction_pipeline, task_id=load_data_to_postgres, run_id=manual__2025-06-04T09:11:13+00:00, execution_date=20250604T091113, start_date=20250604T091146, end_date=20250604T091146
[2025-06-04T09:11:46.766+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 48 for task load_data_to_postgres (Task failed due to SystemExit(1); 229)
[2025-06-04T09:11:46.803+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-04T09:11:46.814+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-04T09:11:46.815+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
